### ISSUE TITLE
google play warning

### ISSUE THREAD

**Issue by mrifni** [readium/kotlin-toolkit#104]
I am running the latest develop branch of the toolkit test app in my production app and received an email from google shown below.

https://support.google.com/faqs/answer/9267555
<img width="1281" alt="Screenshot 2022-04-12 at 16 20 43" src="https://user-images.githubusercontent.com/1643992/162996931-335355d8-8d60-4233-8c02-befc027e295f.png">

package is different but the classes are all same as kotlin toolkit test app

**Comment by mickael-menu** [comment]
I guess Google complains that we're forwarding the input intent. Try with this:

```kotlin
    override fun finish() {
        setResult(Activity.RESULT_OK, Intent().putExtras(intent))
        super.finish()
    }
```

Alternatively, try setting `exported=false` in the manifest for `ReaderActivity`.

If this fixes the issue, please open a pull request on the repo.
