### ISSUE TITLE
IllegalStateException from test app

### ISSUE THREAD

**Issue by mrifni** [readium/kotlin-toolkit#115]
getting this error from live app for few users often. Not sure whats happening. 
I run the same test app so guessing issue persists in test app as well.

Code is based on latest develop branch 2 weeks ago. Error line is 65.

<img width="901" alt="Screenshot 2022-04-28 at 13 47 39" src="https://user-images.githubusercontent.com/1643992/165755433-71fa12e3-3d1c-4c73-8e5a-34e1169564c6.png">

```
Caused by java.lang.IllegalStateException
Required value was null.
com.testapp.epub_plugin.reader.EpubReaderFragment.onCreate (EpubReaderFragment.java:201)
androidx.fragment.app.Fragment.performCreate (Fragment.java:32)

androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:12)
com.testapp.epub_plugin.reader.ReaderActivity.onCreate (ReaderActivity.java:65)
android.app.Activity.performCreate (Activity.java:7893)

com.android.internal.os.ZygoteInit.main (ZygoteInit.java:995)
```

```
Device
Brand:Xiaomi
Model:Redmi Note 8 Pro
Orientation: Portrait
RAM free: 1.92 GB
Disk free: 9.67 GB

Operating System
Version:Android 10
Orientation: Portrait
Rooted:No

```

**Comment by mickael-menu** [comment]
It's hard to say as the line numbers don't match the Kotlin versions but the JVM ones, but I guess it crashes here:

https://github.com/readium/kotlin-toolkit/blob/540c80fc1c57f04d09db45764f103724177aedf9/test-app/src/main/java/org/readium/r2/testapp/reader/EpubReaderFragment.kt#L77

Check that your `readerData` is correctly filled and has the `baseUrl`.

**Comment by mrifni** [comment]
error isnt coming to all the users but for like 10% of the users. There is something else going on here.

**Comment by mickael-menu** [comment]
Closing as I don't think there's anything to fix in the toolkit.

**Comment by mabacy** [comment]
I have same issue as you described @mrifni, can you please support me if you solved it
