### ISSUE TITLE
Build fails: android-pdf-viewer-2.8.2.pom can't be found

### ISSUE THREAD

**Issue by chrfalch** [readium/kotlin-toolkit#125]
## Bug Report

Hi,

I've created a new React Native App and installed the latest versions of the Readium toolkits in the React Native Android / iOS projects. On iOS everything builds fine, while on Android I'm getting an error message when trying to run the app. 

### What happened?

```
Could not HEAD 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status code 401 from server: Unauthorized
```

### Expected behavior

The build should complete successfully and the app should start.

### How to reproduce?

Create a new React Native App:

`npx react-native init ReadiumTest--template react-native-template-typescript`

`cd ReadiumTest`

* Update android/build.gradle according to the documentation (add readium_version, jitpack.io repo is already there)
* Update android/app/build.gradle according to the documentation (add dependencies to the Readium Kotlin-toolkit)

`npx react-native run-android`

### Environment

* Readium version: 2.2.0

#### Development environment

* OS: MacOS 12.4
* IDE: Android Studio 2021.2.1

### Additional context

Build log:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
     Required by:
         project :app > com.github.readium.kotlin-toolkit:readium-navigator:2.2.0
      > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
         > Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
            > Could not HEAD 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status code 401 from server: Unauthorized

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

**Comment by chrfalch** [comment]
For reference, the solution to this problem is to make sure that `jcenter` is still in the list of repositories in the root build.gradle file - then the build works and everything is fine.

**Comment by stevenzeck** [comment]
Yep, `jcenter()` is needed as a repository in the gradle files until #31 is resolved.

**Comment by hishampro5** [comment]
I add the jcenter() and same issue come with me any help plz 

add on **settings.gradle**  on :
pluginManagement{
repositories {
jcenter()
}
}

and on 
dependencyResolutionManagement{
repositories {
jcenter()
}
}

**Comment by hishampro5** [comment]
@chrfalch @stevenzeck plz help here .. i am blocked i cant work with team ... my team has same code and works fine with them why with me not worked ?

**Comment by chrfalch** [comment]
The latest versions of Kotlin Toolkit supports this fine now - so you should upgrade your toolkit version - without it I'm unable to help unfortunately :) Good luck!
