### ISSUE TITLE
Streamer onCreatePublication applied twice

### ISSUE THREAD

**Issue by sdsantos** [readium/kotlin-toolkit#134]
### What happened?

By looking at the code, it seems the `onCreatePublication` lambda is being applied twice to the `Publication.Builder`:

https://github.com/readium/kotlin-toolkit/blob/540c80fc1c57f04d09db45764f103724177aedf9/readium/streamer/src/main/java/org/readium/r2/streamer/Streamer.kt#L137

```
        // Transform provided by the reading app in `Streamer.open()`.
        builder.apply(onCreatePublication)

        val publication = builder
            .apply(onCreatePublication)
            .build()
            .apply { addLegacyProperties(asset.mediaType()) }
```

### Expected behavior

It should only be applied once.

### How to reproduce?

Open a publication using the `Streamer` class.

### Additional context

This bug will only have an impact if the lambda provided is not idempotent.

**Comment by mickael-menu** [comment]
Good point, thank you!

You can open a PR if you want, otherwise I'll fix it this Friday.
