### ISSUE TITLE
Replace ViewPager with RecyclerView + SnapHandler

### ISSUE THREAD

**Issue by ErikHellman** [readium/kotlin-toolkit#150]
The ViewPager solution currently used relies on fragments, which makes the navigator component a bit heavy on fragment use. A better approach would be to use a RecyclerView with a SnapHandler. This would also make the nested scrolling happening today much simpler, as RecyclerView supports this in a better way.

**Comment by mickael-menu** [comment]
We can follow-up in this thread: https://github.com/readium/kotlin-toolkit/discussions/51#discussioncomment-3280487
