### ISSUE TITLE
EPUB 2 meta tags should be superseded by EPUB 3 ones

### ISSUE THREAD

**Issue by mickael-menu** [readium/kotlin-toolkit#196]
When an OPF contains both an EPUB 2 (`<meta name=>`) and EPUB 3 (`<meta property=>`) meta tags for the same key, the EPUB 3 ones should take precedence and the EPUB 2 ones ignored. Currently both are added to the `otherMetadata` dictionary.

Here's an example:

```xml
<meta property="media:active-class">-epub-media-overlay-active</meta>
<meta name="media:active-class" content="text-highlight" />
```

[See the decision in the last meeting minutes](https://docs.google.com/document/d/1QKWhtVd9Ey8fO7BfmUsoDmON2j37Xho-IWPycTWreV4/edit?usp=sharing).

**Comment by qnga** [comment]
By definition, what ends up in `otherMetadata` is not well-known and agnostic to the property: you can't know if the property is single or multiple value. As sometimes Epub 2 style properties appear even in EPUB 3, we can't ignore them. I don't know how we can deal with that (it looks like I attended this meeting, my bad).

**Comment by mickael-menu** [comment]
Yes that's the idea. I updated the OP.
