### ISSUE TITLE
Web Storage is not available

### ISSUE THREAD

**Issue by JayPanoz** [readium/kotlin-toolkit#225]
When testing the origin for Web Storage across our test apps, it looked like it isn’t currently available in the Android test app. 

My understanding is that [this is opt-in for Android web views](https://developer.android.com/reference/android/webkit/WebSettings.html#setDatabaseEnabled(boolean)) but I couldn’t find any occurrence of `setDatabaseEnabled` with a quick search. Please correct me if I’m wrong, obviously. If it is indeed enabled, then there’s another bug preventing it from being used somewhere.

Of course the next issue is managing the origin on a publication basis. A lot of existing Reading Apps on Android don’t do this, so you can access data from other publications and remove them. 

[See Dan’s doc for further details](https://github.com/edrlab/r2-streamer-js/blob/develop/docs/origin.md) if needed.

**Comment by qnga** [comment]
Database Storage is deprecated, so this is issue is superseded by #266 about Local Storage.
