### ISSUE TITLE
Overlapping phrases

### ISSUE THREAD

**Issue by mricgar** [readium/kotlin-toolkit#274]
Running the latest (2.2.0) on a real device (Huawei P20pro)
Also reproduced in the test app

Please see the attached video

1. Open book
2. Activate scroll mode
3. Scroll down to the end of the chapter
4. Disable scroll mode
5. Navigate between pages horizontally
6. See error

https://user-images.githubusercontent.com/56269361/191031671-e8b2b3be-27b9-4ece-b9b2-935f49acda2e.mp4

**Comment by 838** [comment]
We also experience the same issue in our app when the app is resumed after it has been in the background for a while. 

![screenshot](https://user-images.githubusercontent.com/3314171/191215128-8befd19c-19d7-434c-98d9-2bc676ba642f.png)

**Comment by mickael-menu** [comment]
I can't reproduce the problem, could you share the book you used in your video?

**Comment by mricgar** [comment]
I share a video playing in the test app with one of the available books. I think this will be more useful

https://user-images.githubusercontent.com/56269361/191919893-c07c0a9c-b36c-4d45-9988-3e61b7250d6f.mp4

**Comment by mickael-menu** [comment]
Unfortunately I can't fix the problem if I can't reproduce it myself. It looks like a rendering bug in the web view.

**Comment by mricgar** [comment]
How can we help you?

**Comment by mickael-menu** [comment]
If you could share with me one of the book exhibiting the issue, maybe I can reproduce it this way. Otherwise try debugging the toolkit yourself to find clues.

**Comment by mickael-menu** [comment]
Also you could try using `git bisect` on the toolkit to find which commit introduced the issue, if it's a regression.

**Comment by mickael-menu** [comment]
Good news, I wasn't looking for this but it happened on my device. The issue is the computation of the Readium CSS `--RS__viewportWidth` which uses an incorrect null width. I'll investigate some more.

```css
 --RS__viewportWidth:calc(0px / 2.75);
```

**Comment by mricgar** [comment]
Great! yes, in this fixed "fix/null-viewport-width" it no longer happens to me

**Comment by mricgar** [comment]
¿Do you have an approximate date (months) for the next version is out?

**Comment by mickael-menu** [comment]
It should be pretty soon now, we're just finalizing the new Settings API for PDF and then we'll do a new release. A matter of weeks.
