### ISSUE TITLE
Does not refresh when modifying line height

### ISSUE THREAD

**Issue by mricgar** [readium/kotlin-toolkit#275]
With the application installed from scratch, in the first book that you enter and modify its line height, it does not refresh. You have to log out and back in for this to work.

Also reproduced in the test app
This is version 2.2.0 but it has also happened in a 2.2.1 that was installed on another device
It always happens the first time after clearing cache and app data.

https://user-images.githubusercontent.com/56269361/191048322-1146d5bd-7285-499c-95c7-468792b1d06a.mp4

**Comment by mickael-menu** [comment]
I could reproduce the issue, but this seems already fixed in `develop` with [the new Settings API](https://github.com/readium/kotlin-toolkit/pull/141).

**Comment by mickael-menu** [comment]
But if you want to fix it in the current version for your app, make sure that the "publisher defaults" is properly turned off when changing the line height. It's probably an issue in the user settings examples you copied from the test app.

**Comment by mricgar** [comment]
Thanks a lot. i managed to fix it
