### ISSUE TITLE
highlight not functioning correctly.

### ISSUE THREAD

**Issue by badlirashid** [readium/kotlin-toolkit#284]
Hi,

I was not able to highlight properly. when selecting the text to highlight it jumps to another area. Or highlighting is sensitive.

https://user-images.githubusercontent.com/489256/194165230-9e64dc4d-fc98-4808-b520-07fea3ac0b74.mp4

**Comment by mickael-menu** [comment]
Hi, could you open a new issue following [the bug report issue template](https://github.com/readium/kotlin-toolkit/issues/new?assignees=&labels=&template=bug_report.md&title=)? Thank you.

**Comment by badlirashid** [comment]
> Hi, could you open a new issue following [the bug report issue template](https://github.com/readium/kotlin-toolkit/issues/new?assignees=&labels=&template=bug_report.md&title=)? Thank you.

Hi mikael,

Thank you but just close. i have try another app, the issue i was having with a particular epub file seem to have been fix.

Regards,
Badli

**Comment by Hardovsky** [comment]
Hi, i have this behavior with all my epub books
