### ISSUE TITLE
I'm having an issue pulling com.github.edrlab.nanohttpd:nanohttpd:master-SNAPSHOT

### ISSUE THREAD

**Issue by alexwhb** [readium/kotlin-toolkit#286]
This is not a bug per se, just wanted to see if anyone else is experiencing an issue with this. 
Just randomly started happening out of the blue today. It has been working just fine for the last year or so. 

Here's what my gradle build is saying: ```Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find nanohttpd-nanolets-master-SNAPSHOT.jar (com.github.edrlab.nanohttpd:nanohttpd-nanolets:master-SNAPSHOT:nanohttpd-project-2.3.1-gc3b149e-77).```

**Comment by stevenzeck** [comment]
Yeah, something changed with the nanohttpd repository. The current workaround, suggested in Slack, is using the below block in your root `build.gradle.kts` file (adjust if using groovy).

```
allprojects {
	configurations.all {
        resolutionStrategy.eachDependency {
            if (requested.group == "com.github.edrlab.nanohttpd" && requested.name == "nanohttpd") {
                useTarget("com.github.readium.nanohttpd:nanohttpd:master-SNAPSHOT")
            }
            if (requested.group == "com.github.edrlab.nanohttpd" && requested.name == "nanohttpd-nanolets") {
                useTarget("com.github.readium.nanohttpd:nanohttpd-nanolets:master-SNAPSHOT")
            }
        }
    }
}
```

**Comment by TheEnsis** [comment]
> Yeah, something changed with the nanohttpd repository. The current workaround, suggested in Slack, is using the below block in your root `build.gradle.kts` file (adjust if using groovy).
> 
> ```
> allprojects {
> 	configurations.all {
>         resolutionStrategy.eachDependency {
>             if (requested.group == "com.github.edrlab.nanohttpd" && requested.name == "nanohttpd") {
>                 useTarget("com.github.readium.nanohttpd:nanohttpd:master-SNAPSHOT")
>             }
>             if (requested.group == "com.github.edrlab.nanohttpd" && requested.name == "nanohttpd-nanolets") {
>                 useTarget("com.github.readium.nanohttpd:nanohttpd-nanolets:master-SNAPSHOT")
>             }
>         }
>     }
> }
> ```

Thank you for the work around, I also met this issue yesterday and now it work fine.
Looking forward to the next update 😃

**Comment by m-ochyra** [comment]
I have the same issue, and workaround is not working
`
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.readium.nanohttpd:nanohttpd:master-SNAPSHOT.
     Required by:
         project :app > project :my_project
         project :app > project :my_project > com.github.readium.kotlin-toolkit:readium-streamer:2.1.1
      > Skipped due to earlier error
   > Could not resolve com.github.readium.nanohttpd:nanohttpd-nanolets:master-SNAPSHOT.
     Required by:
         project :app > project :my_project
         project :app > project :my_project > com.github.readium.kotlin-toolkit:readium-streamer:2.1.1
      > Skipped due to earlier error
`

**Comment by paktalin** [comment]
> I have the same issue, and workaround is not working

probably related to nitpick server being down, check the [GitHub issue](https://github.com/jitpack/jitpack.io/issues/5239). Very frustrating... 😕

**Comment by mickael-menu** [comment]
@m-ochyra Do you still have the issue with the workaround?

**Comment by mickael-menu** [comment]
[There's a new 2.2.1 release for this issue](https://github.com/readium/kotlin-toolkit/releases/tag/2.2.1). Make sure to follow the migration guide to upgrade.

## Migration Guide


This hotfix release fixes an issue [pulling a third-party dependency (NanoHTTPD) from JitPack](https://github.com/readium/kotlin-toolkit/issues/286).

After upgrading, make sure to remove the dependency to NanoHTTPD from your app's `build.gradle` file before building:

```diff
-implementation("com.github.edrlab.nanohttpd:nanohttpd:master-SNAPSHOT") {
-    exclude(group = "org.parboiled")
-}
-implementation("com.github.edrlab.nanohttpd:nanohttpd-nanolets:master-SNAPSHOT") {
-    exclude(group = "org.parboiled")
-}
```

:point_up: If you are stuck with an older version of Readium, you can [use this workaround in your root `build.gradle`](https://github.com/readium/kotlin-toolkit/issues/286#issuecomment-1283408861), as an alternative.

**Comment by m-ochyra** [comment]
> @m-ochyra Do you still have the issue with the workaround?

No, I have no issue. It's working

**Comment by M-HARIS-97** [comment]
The problem is encountered again.

![image](https://user-images.githubusercontent.com/57429370/209139443-76fe75d2-7d73-4c9b-abf6-c74c1f59f76a.png)

**Comment by jspizziri** [comment]
@M-HARIS-97 it looks like jitpack is having some sort of an outage, which is causing this issue.

**Comment by MurasameAya** [comment]
The problem is encountered again
<img width="400" alt="1678155018(1)" src="https://user-images.githubusercontent.com/52487645/223301380-9aadae6a-6cae-4b83-8ce5-632e4a5ca950.png">

**Comment by mickael-menu** [comment]
Upgrade to 2.3.0 which embeds NanoHTTPd as a JAR. You will need to remove any mention of NanoHTTPd from your `build.gradle` files.

**Comment by mickael-menu** [comment]
Also Readium (since 2.3.0) is now distributed in Maven Central.
