### ISSUE TITLE
Epub - rendering errors after font size adjustment

### ISSUE THREAD

**Issue by mkwiatek1978** [readium/kotlin-toolkit#296]
## Bug Report

- Epub file is opened with the default font settings.
- User enlarges the font size to the maximum
- Bug: the text is rendered with errors. Some letters overlap and obscure each other.
- App revision number: 30c729636be4057a9144f2dd6ee3428309088fe1
- Movie attached
- 

https://user-images.githubusercontent.com/56821812/200568961-6487c09c-e4cd-4039-b5d7-dedeca8ffa26.mp4

**Comment by mickael-menu** [comment]
I'm not sure how to address this one.

There's not enough room to display the word entirely in the viewport, so the CSS columns are overlapping. If you disable publisher styles and enable hyphenation, it should help.

Without hyphenation:

<img src="https://user-images.githubusercontent.com/58686775/201987754-203194d6-2c76-4774-b060-8c347fb2b2c9.png" width="200px"/>

With hyphenation:

<img src="https://user-images.githubusercontent.com/58686775/201987749-737955ba-5bcc-4bfd-9e6b-0b3001e27b62.png" width="200px"/>

I think we can reduce the maximum size for the font size, but the font size range can be customized by each app anyways.
