### ISSUE TITLE
R2BasicWebView.Listener#resourceAtUrl should probably have a default value

### ISSUE THREAD

**Issue by sdsantos** [readium/kotlin-toolkit#312]
Testing out the latest version at `develop` and noticed a small thing that was probably missed. The method `resourceAtUrl` at `R2BasicWebView.Listener` should probably have a default value `null` like the other new methods tagged with `@InternalReadiumApi`.

**Comment by mickael-menu** [comment]
Good point, I fixed it in https://github.com/readium/kotlin-toolkit/pull/305
