### ISSUE TITLE
Migration from 'develop-snapshot' to 2.2.1

### ISSUE THREAD

**Issue by pratyushITC** [readium/kotlin-toolkit#321]
1-> In our Readium toolkit implementation we get the license followed by importing and processing publication in order to get the .epub file which is used to open the Reader screen of Any Ebook. We are able to successfully get the .lcpl and .epub file but unable to see any content. Please refer below code for the process of implementing the last part regarding opening the reader screen.

   protected suspend fun importPublication() {
        var sourceFile: File? = null
        if (bookType == Constants.PDF)
            sourceFile = File(Helper.getPdfLicenseStoredPath(isbn, applicationContext))
        else
            sourceFile = File(Helper.getLicenseStoredPath(isbn, isEBook, applicationContext))

        Log.e("bookPath", "${sourceFile.absolutePath}")
        lcpService.acquirePublication(sourceFile, isbn, bookType, ::downloadProgress).fold(

            {
                if (bookType == Constants.PDF) {
                    openPublication(FileAsset(it.localFile, MediaType.LCP_PROTECTED_PDF))
                } else {
                    openPublication(FileAsset(it.localFile, MediaType.EPUB))
                }

            },
            {
                Log.e("importPublication", it.message.toString())
                Timber.d(it)
                AlertDialog.alertWithFinishActivity1(
                    this@EbookDownloadActivity, "",
                    resources.getString(R.string.error_gb_009)
                )
                return
            }
        )

    }

    protected suspend fun openPublication(libraryAsset: FileAsset) {
        hideProgress()
        showBookLoadingDialog()
        streamer.open(libraryAsset, allowUserInteraction = true, sender = this)
            .onSuccess { publication ->
                if (publication.isRestricted) {
                    publication.protectionError?.let { error ->
                        Log.e("TestError", "${error.getUserMessage(applicationContext).toString()}")
                        alert?.let {
                            it.dismiss()
                        }
                        //This license expired on
                        if (error.getUserMessage(applicationContext)
                                .contains("This license expired on")
                        )
                            AlertDialog.bookExpiredAlert(
                                this@EbookDownloadActivity, ::bookExpiredCallback,

                                )
                        else
                            AlertDialog.alertWithFinishActivity1(
                                this@EbookDownloadActivity, "",
                                getResources().getString(R.string.error_gb_009)
                            )
                        Timber.d(error)
                        tryOrNull {
                            libraryAsset.file.delete()
                        }

                    }
                } else {
                    UApplication.prepareToServe(publication)?.let { baseUrl ->
                        launch(Dispatchers.Main) {
                            openReaderScreen(
                                publication,
                                baseUrl,
                                libraryAsset,
                                Locator.fromJSON(JSONObject("{}"))!!
                            )
                        }
                    }
                }

            }
            .onFailure {
                Log.e("Error-check", it.localizedMessage)
                Timber.d(it)
                AlertDialog.alertWithFinishActivity1(
                    this@EbookDownloadActivity, "",
                    resources.getString(R.string.error_gb_009)
                )
            }
    }

    fun openReaderScreen(
        publication: Publication,
        baseUrl: URL,
        asset: FileAsset,
        initialLocator: Locator
    ) {
        alert?.let {
            if (alert?.isShowing!!) {
                alert?.dismiss()
            }
        }

        val readerInitData = openVisual(publication, initialLocator)

        val arguments = ReaderActivityContract.Arguments(1)
        readerLauncher.launch(arguments)
        finish()
    }

    private fun openVisual(
        publication: Publication,
        initialLocator: Locator?
    ): VisualReaderInitData {
        val url = prepareToServe(publication)
        return VisualReaderInitData(1,publication, url, initialLocator)
    }

2-> How can we open the ebook without using the bookId. We have following data with us which was used with the older 'develop-snapshot' version.
	putPublication(publication)
            putExtra("baseUrl", baseUrl.toString())
            putExtra("publicationPath", asset.file.absolutePath)
            putExtra("publicationFileName", asset.name)
            putExtra(Constants.ISBN, isbn)
			
Note:- We are upgrading from 'develop-snapshot' to '2.2.1' version. We have added all the modules from the Test App

**Comment by mickael-menu** [comment]
`develop-SNAPSHOT` could be any version so it's hard to know what you need to do. Find out the actual release version by comparing the date of your snapshot with the releases: https://github.com/readium/kotlin-toolkit/releases

Then once you know which Readium version you used, follow all the intermediary migration steps from https://github.com/readium/kotlin-toolkit/blob/main/docs/migration-guide.md

**Comment by pratyushITC** [comment]
@mickael-menu We have referred the migration guide and the sample test app. We are doing everything same as per testapp except the bookId part. 
 How can we open the ebook without using the bookId. What else can be used in the absence of bookId? We have following data with us. Which Activity in the readium toolkit will accept this data in order to open ebook. Please refer below Intent data available with us which is working in older version of the SDK. This is a blocker for us while updating SDK. Kindly help

putPublication(publication)
putExtra("baseUrl", baseUrl.toString())
putExtra("publicationPath", asset.file.absolutePath)
putExtra("publicationFileName", asset.name)
putExtra(Constants.ISBN, isbn)

**Comment by mickael-menu** [comment]
I don't understand your question with `bookId`, this is not needed by the toolkit if you use `EpubNavigatorFragment`.

**Comment by pratyushITC** [comment]
@mickael-menu Can we use below code to open any ebook/PDF. If not please suggest what to change here?

var readerScreenIntent: Intent? = null
        if (bookType == Constants.PDF)
            readerScreenIntent = Intent(this, ReaderActivity::class.java)
        else
            readerScreenIntent = Intent(this, R2EpubActivity::class.java)

        readerScreenIntent.apply {
            putPublication(publication)
            putExtra("baseUrl", baseUrl.toString())
            putExtra("publicationPath", asset.file.absolutePath)
            putExtra("publicationFileName", asset.name)
            putExtra(Constants.ISBN, isbn)
            putExtra(Constants.sellerid, sellerId)
        }
        Log.d("ebookdownloadactivity","baseurl"+publication.baseUrl.toString())

        startActivity(readerScreenIntent)

**Comment by mickael-menu** [comment]
I think it's okay, but you should migrate to `EpubNavigatorFragment` which is easier to use. `R2EpubActivity` will be deprecated soon.

**Comment by pratyushITC** [comment]
1. We are passing the data Which we posted earlier to R2EpubActivity but the reader screen opens as a blank page. We are not even getting any error in this case? Please suggest how to resolve this. 

2. How can we implement EpubNavigatorFragment instead of R2EpubActivity?
 
3. While trying alternate solutions in order to bypass bookId logic, I have passed data in the ReaderActivityContract as below:
fun parseIntentt(activity: Activity): Input = with(activity) {
            Input(
                file = File(intent.getStringExtra("publicationPath")!!),
                mediaType = null,
                publication = intent.getPublication(activity),
                bookId = intent.getLongExtra("bookId", -1),
                initialLocator = intent.getParcelableExtra("locator"),
                deleteOnResult = intent.getBooleanExtra("deleteOnResult", false),
                baseUrl = URL(intent.getStringExtra("baseUrl"))
            )
        }
 
But in the ReaderViewModel we are getting **java.lang.IllegalStateException: This job has not completed yet** for the below line in the below method. What needs to be used to get ReaderInitData here?
val readerRepository = application.readerRepository.getCompleted()
 

class Factory(
        private val application: UApplication,
        private val arguments: ReaderActivityContract.Input
    ) : ViewModelProvider.NewInstanceFactory() {
 
        @Suppress("UNCHECKED_CAST")
        override fun <T : ViewModel> create(modelClass: Class<T>): T =
            when {
                modelClass.isAssignableFrom(ReaderViewModel::class.java) -> {
                    val readerInitData =
                        try {
                            **val readerRepository = application.readerRepository.getCompleted()**
                            readerRepository[arguments.bookId]!!
                        } catch (e: Exception) {
                            // Fallbacks on a dummy Publication to avoid crashing the app until the Activity finishes.
                            dummyReaderInitData(arguments.bookId)
                        }
                    ReaderViewModel(readerInitData, application.bookRepository) as T
                }
                else ->
                    throw IllegalStateException("Cannot create ViewModel for class ${modelClass.simpleName}.")
            }
 
        private fun dummyReaderInitData(bookId: Long): ReaderInitData {
            val metadata = Metadata(identifier = "dummy", localizedTitle = LocalizedString(""))
            val publication = Publication(Manifest(metadata = metadata))
            return VisualReaderInitData(bookId, publication)
        }
    }

**Comment by mickael-menu** [comment]
To use the `EpubNavigatorFragment`, take a look at the examples either in the test app, or in this other discussion: https://github.com/readium/kotlin-toolkit/discussions/54#discussioncomment-792210

**Comment by khalidaITC** [comment]
what will be the parent Activity for EpubNavigatorFragment? How about 1st and 3rd points?

**Comment by mickael-menu** [comment]
> what will be the parent Activity for EpubNavigatorFragment?

Your own reader activity with your own UI (action bar, etc.). In the latest test app, this is `r2.testapp.reader.ReaderActivity`.

> How about 1st and 3rd points?

I can provide support for the toolkit APIs but not the app code, even if it was copy-pasted from the test app.
