### ISSUE TITLE
Migration to Readium Kotlin toolkit v2.2.1

### ISSUE THREAD

**Issue by pratyushITC** [readium/kotlin-toolkit#322]
Please refer below ticket for reference regarding issues during migration.

https://github.com/readium/kotlin-toolkit/issues/321 - Reference Ticket

We have referred the migration guide and the sample test app. We are doing everything same as per testapp except the bookId part.
How can we open the ebook without using the bookId. What else can be used in the absence of bookId? We have following data with us. Which Activity in the readium toolkit will accept this data in order to open ebook. Please refer below Intent data available with us which is working in older version of the SDK. This is a blocker for us while updating SDK. Kindly help

putPublication(publication)
putExtra("baseUrl", baseUrl.toString())
putExtra("publicationPath", asset.file.absolutePath)
putExtra("publicationFileName", asset.name)
putExtra(Constants.ISBN, isbn)

**Comment by mickael-menu** [comment]
Duplicates of https://github.com/readium/kotlin-toolkit/issues/321
