### ISSUE TITLE
Epub Landscape scaling

### ISSUE THREAD

**Issue by DominikKu** [readium/kotlin-toolkit#336]
### What happened?

In landscape orientation content not scale to display.
Video - https://drive.google.com/file/d/1gdzPFsTCfcNHY8ZnbNp8GR0fjljhCqdj/view?usp=sharing
Example epub - https://drive.google.com/file/d/1CnAH1WKshUpa3Clv2i3WY99vfKmbFYkO/view?usp=sharing

### How to reproduce?

1.Open epub.
2. Change screen orientation.

### Environment

Android : 11
Device : One Plus 6
Readium version: develop branch - 20.01.2023, commit https://github.com/readium/kotlin-toolkit/commit/af2f764020c252d5ccf69e94e4956e4c7769520a

**Comment by mickael-menu** [comment]
It's a know issue, but we won't fix this in the current iteration of the FXL navigator. We plan to create a brand new FXL EPUB navigator this year.

**Comment by superjohan** [comment]
This seems to still be an issue, at least with fixed layout epubs.
