### ISSUE TITLE
EPUB files are not being parsed correctly when read aloud

### ISSUE THREAD

**Issue by Pinky-245** [readium/kotlin-toolkit#339]
Our goal is to develop a non-visual reading app that uses speech-based technology to read commonly used file types such as EPUB. To accomplish this, we are studying the Thorium Android app as a reference. However, during our analysis, we noticed that certain parts of the files are not being read aloud, while some parts are being repeated multiple times. This issue appears to stem from parsing problems within the app. Furthermore, we discovered that the app does not provide table of contents (TOC) navigation or hyperlink navigation when using the Text to Speech feature.

**Comment by mickael-menu** [comment]
This feature is currently being worked on and the `develop` branch as some issues with TTS. Did you try from the 2.3.0/`main` or `develop`?

If you have the same issues on `main`, some samples would be helpful to have actionable items for this:
>However, during our analysis, we noticed that certain parts of the files are not being read aloud, while some parts are being repeated multiple times.

**Comment by Pinky-245** [comment]
@mickael-menu  I have noticed an announcement here  https://github.com/readium/kotlin-toolkit/blob/2.3.0/docs/guides/tts.md so May I know the tentative timeline of it. 

I have clone 2.3.0/main and tested that but still, there are issues like latency, TOC navigation when read aloud.

**Comment by mickael-menu** [comment]
> May I know the tentative timeline of it.

A couple of weeks, I think.

> TOC navigation when read aloud.

This is in the responsibility of host apps. The test app disables the ToC for simplicity, but an app can choose to interrupt and restart the TTS when the user clicks on a ToC item.

**Comment by mickael-menu** [comment]
I'm closing this issue, feel free to reopen a bug report with sample files and examples for more specific individual issues.
