### ISSUE TITLE
somthing error while getting nanohttpd

### ISSUE THREAD

**Issue by MurasameAya** [readium/kotlin-toolkit#340]
use the readium 2.2.1 ver 。
![image](https://user-images.githubusercontent.com/52487645/223328260-24c26c5a-9115-4c73-884f-20ee4b6be802.png)

<img width="342" alt="企业微信截图_16781667226624" src="https://user-images.githubusercontent.com/52487645/223328421-3eb6d698-1d3e-4e28-87cc-b5987a12dcda.png">

**Comment by mickael-menu** [comment]
Upgrade to 2.3.0 which embeds NanoHTTPd as a JAR. You will need to remove any mention of NanoHTTPd from your `build.gradle` files.
