### ISSUE TITLE
Disable of copy/paste in pdf file with readium library

### ISSUE THREAD

**Issue by nageshwararao1988** [readium/kotlin-toolkit#346]
User is able to copy/paste the text from ebook from the Android version 12 and above.
So, need to disable the copy/paste from clipboard for the user from ebook.

**Comment by mickael-menu** [comment]
This is not supported or possible in Readium at the moment.

**Comment by nageshwararao1988** [comment]
Is there tentative date for any kind of updation of library for this issue?

**Comment by nageshwararao1988** [comment]
Hi Mickael,

We are using the free PDF navigator based on PDFium. Let me know if you have any more questions.
