### ISSUE TITLE
Epub javascript interface on readium 2.3.0

### ISSUE THREAD

**Issue by LubomirGanchev** [readium/kotlin-toolkit#355]
Hello, sorry for being late after I first asked this in slack. 

So, we have a js file which is responsible for extracting the text from the footnotes in epub and then deliver it to a function in kotlin to show a popup with the given text. After upgrading to version 2.3.0 and following the migration guide, this functionality is not working anymore, because our js files are not injected into the webview.  In our current version we were injecting the files via the server.loadCustomResource, but not anymore since it is deprecated. We are attaching screenshots and videos from our current version and the new one. I tested it on emulator and real device as well.

This is the functionality on our current version. As you can see "inject.js" and "jquery.js" files are added into the webview
https://github.com/readium/kotlin-toolkit/assets/109721963/f6a4411c-d9c6-4d51-a93b-35d337773bf5
![currentVersion](https://github.com/readium/kotlin-toolkit/assets/109721963/544b8abb-38b1-437d-a8e6-25867a14dd46)

This is on version 2.3.0

https://github.com/readium/kotlin-toolkit/assets/109721963/41b35ca6-4ba1-4775-88d9-676249d0f353
![assets 2 3](https://github.com/readium/kotlin-toolkit/assets/109721963/f1765b64-1502-4b86-b5f3-3426154c8116)

This is where we inject our js and register the javascript interface 
![epubFragment](https://github.com/readium/kotlin-toolkit/assets/109721963/94176af5-877e-44f9-b569-79a7c7554f22)

Would be great if you can point us in the right direction and tell us if something wrong is done on our side.

**Comment by mickael-menu** [comment]
Hmm you did nothing wrong, you need a feature called Injectable API that is not yet implemented in this new version.

The `servedAssets` property is only used to make some asset resources available to the web view with HTTP requests. But it doesn't inject any script in the content.

Until we come up with an easy-to-use Injectable API, you can do the injection manually by transforming the fetcher when creating the `Streamer`, e.g.:

```kotlin
val streamer = Streamer(
    context = context,
    onCreatePublication = {
        if (
            manifest.conformsTo(Publication.Profile.EPUB) &&
            manifest.metadata.presentation.layout == EpubLayout.REFLOWABLE
        ) {
            fetcher = TransformingFetcher(fetcher) { resource ->
                resource.injectScripts()
            }
        }
    }
)

private fun Resource.injectScripts(): Resource =
    TransformingResource(this) { bytes ->
        val link = link()
        if (!link.mediaType.isHtml) {
            return@TransformingResource bytes
        }

        var content = bytes.toString(link.mediaType.charset ?: Charsets.UTF_8).trim()
        val injectables = listOf(
            """<script type="text/javascript" src="https://readium/assets/inject.js"></script>"""
        )

        val headEndIndex = content.indexOf("</head>", 0, true)
        if (headEndIndex != -1) {
            content = StringBuilder(content)
                .insert(headEndIndex, "\n" + injectables.joinToString("\n") + "\n")
                .toString()
        }

        content.toByteArray()
    }
```

The assets you declare with `servedAssets` are available under the base URL `https://readium/assets/`.

**Comment by mickael-menu** [comment]
I'm glad 👍
