### ISSUE TITLE
Failing build due to missing JCenter dependencies

### ISSUE THREAD

**Issue by ivstiv** [readium/kotlin-toolkit#359]
## Bug Report

Our builds started failing recently when jCenter started redirecting to Maven Central. ([Somebody else has noticed it as well](https://www.reddit.com/r/androiddev/comments/14g840g/jcenter_finally_down_for_good/)) We discovered the issue when building the react-native-readium wrapper on expo (as our dev machines already had the package cached). I don't know if the issue is with this project but looking at the error it seems like the kotlin-toolkit is relying on packages that have not been published anywhere else but jCenter.

```
[stderr] 
FAILURE:
[stderr] 
Build failed with an exception.
[stderr] 
* What went wrong:
[stderr] 
Could not determine the dependencies of task ':app:buildReleasePreBundle'.
[stderr] 
>
[stderr] 
Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
[stderr] 
>
[stderr] 
Could not find com.shopgun.android:utils:1.0.9.
[stderr] 
Searched in the following locations:
[stderr] 
- http://10.4.1.4:8081/artifactory/libs-release/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
[stderr] 
       - file:/home/expo/.m2/repository/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
[stderr] 
       - file:/home/expo/workingdir/build/node_modules/react-native/android/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
[stderr] 
       - file:/home/expo/workingdir/build/node_modules/jsc-android/dist/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
[stderr] 
       - https://dl.google.com/dl/android/maven2/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
[stderr] 
       - https://repo.maven.apache.org/maven2/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
[stderr] 
       - https://www.jitpack.io/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
[stderr] 
       - https://plugins.gradle.org/m2/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
[stderr] 
     Required by:
[stderr] 
         project :app > project :react-native-readium > com.github.readium.kotlin-toolkit:readium-navigator:2.2.1
```

https://mvnrepository.com/artifact/com.shopgun.android/utils

Perhaps a solution could be to find the library somewhere and republish it in our own repository for now? Anybody else facing this?

### Environment

* Readium version:

#### Development environment

* OS: 
* IDE: 

#### Testing device

* Android version:
* Model: 
* Is it an emulator? Yes or No

### Additional context

* Are you willing to fix the problem and contribute a pull request? Yes or No

**Comment by mickael-menu** [comment]
Do you still have the problem with Readium 2.3.0? It seems to work fine from my clone.

Caveat: The PDFium adapter (`com.github.readium.kotlin-toolkit:readium-adapter-pdfium`) still depends on JCenter, so for now it is down. But the rest of the toolkit should work fine.

**Comment by ivstiv** [comment]
We are using whatever the react-native-readium project links to
https://github.com/5-stones/react-native-readium/blob/1d3257e74a09ee6cbb34f7aab0ba522d19d67e34/android/build.gradle#L142-L145

which seems to be 2.2.1. Does it need bumping to 2.3.0? I will fork and give it a go to see if it gets resolve anyway.

**Comment by mickael-menu** [comment]
Yes, it needs to be upgraded.

**Comment by mickael-menu** [comment]
This PR removed the JCenter dependencies from the main toolkit modules: https://github.com/readium/kotlin-toolkit/pull/314, so 2.3.0 should fix it.

**Comment by mickael-menu** [comment]
They seem to have restored JCenter: https://status.gradle.com/incidents/7x4wqd7zv715

However, I'll take a look to remove the last dependency using JCenter: PDFium.

**Comment by qnga** [comment]
I close this issue, keeping #31 open.
