### ISSUE TITLE
Epub onTap "freeze" on device rotation

### ISSUE THREAD

**Issue by LubomirGanchev** [readium/kotlin-toolkit#360]
### What happened?
When device is rotated in landscape for example, the onTap functionality seems to stop working. It doesn't seems to fix itself after rotating the device back to the original orientation. As I said in slack it happens on certain devices/models. For example it never happened on my personal OnePlus Nord (android 12). I am attaching a video captured on emulator using the readium test app.
### How to reproduce?
Open the test app and load a book (in this example i used Le Mystere from the OPDS Test catalog). Once the book is loaded rotate the device orientation and tap in the middle or the sides.

https://github.com/readium/kotlin-toolkit/assets/109721963/7be1ed47-05fa-4b39-b99e-c5c4eca550fb

### Environment

* Readium version: 2.3.0

#### Development environment

* OS: Windows 11
* IDE: Android Studio Chipmunk | 2021.2.1 Patch 2

#### Testing device

* Android version:
* Model: Xiaomi 11 Lite 5G NE | MIUI 14.0.6
* Is it an emulator? No
----------------------------
* Android version:
* Model: Pixel 5 API 33
* Is it an emulator? Yes

### Additional context

**Comment by mickael-menu** [comment]
@LubomirGanchev Let me know if this helps: https://github.com/readium/kotlin-toolkit/pull/361

**Comment by LubomirGanchev** [comment]
Hi Michael, sorry for the late answer, but this change seems to fix the problem!
