### ISSUE TITLE
Different css behaviour when baseUrl is null

### ISSUE THREAD

**Issue by ivstiv** [readium/kotlin-toolkit#386]
## Bug Report

I think due to the following ternary people who want to have highlighting and LCP would run into problems with text selection.
https://github.com/readium/kotlin-toolkit/blob/830812b02a0597b4b22d0d37ec35846db24cb0a4/readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorViewModel.kt#L394-L398

So far from my experience when trying to use the EpubNavigatorFragment I get different behaviour for the `disableSelectionWhenProtected` in the config when passing/not passing baseUrl.

```kotlin
childFragmentManager.fragmentFactory =
            EpubNavigatorFragment.createFactory(
                publication = publication,
                baseUrl = baseUrl,
                initialLocator = model.initialLocation,
                listener = this,
                config = EpubNavigatorFragment.Configuration().apply {
                    selectionActionModeCallback = customSelectionActionModeCallback
                    disableSelectionWhenProtected = false
                }
            )
```

When baseUrl is passed in the publication doesn't use the escape hatch introduced by [this PR](https://github.com/readium/kotlin-toolkit/pull/303) because it only exists in the WebViewServer. I don't understand how does it work with the server being null but if I remove the baseUrl to force the other side of the branching logic and use the instance of the WebViewServer, the escape hatch for  `disableSelectionWhenProtected` starts working but the background colour and potentially some other css settings are not being set.

So I effectively need to choose between being able to select text or have the correct preferences set from the get go. A later change in the settings is reflected correctly and does update the UI.

Is this really a bug or am I misusing the fragment somehow? 

### Environment

* Readium version:

#### Development environment

* OS: 
* IDE: 

#### Testing device

* Android version:
* Model: 
* Is it an emulator? Yes or No

### Additional context

* Are you willing to fix the problem and contribute a pull request? Yes or No

**Comment by mickael-menu** [comment]
Hi,

Did you do the HTTP server + Preferences API migration [as explained here](https://github.com/readium/kotlin-toolkit/blob/develop/docs/migration-guide.md#removing-the-http-server)? This is necessary for `disableSelectionWhenProtected` to work.

**Comment by ivstiv** [comment]
Ahh yes this looks like what I am after. It would explain why when I drop the baseUrl my user preferences don't work initially. Thank you very much for this! Can you please leave the issue open for now I will follow the guides and come back if something pops up that is related to this, else I will close it.
