### ISSUE TITLE
Attempting to highlight makes the page jump backwards in ebooks with long paragraphs

### ISSUE THREAD

**Issue by radusalagean** [readium/kotlin-toolkit#417]
### What happened?

Some users reported the following unwanted behavior when using the highlight feature: attempting to highlight a section makes the e-reader jump a few pages backwards on some books, while holding the finger down to select the desired text.

I took one of the books that our users reported and opened it with the Readium Sample App. The same unwanted behavior happens there as well.

Since this issue happens only on some books, I opened it with the [Sigil EPUB Editor](https://sigil-ebook.com/sigil/) and then opened another EPUB in another window where this issue does not appear. I took a book from the OPDS 2.0 Test Catalog, accessible from the Sample App as a reference book.

The striking difference between them was that the book our users reported the issue on, had that entire chapter as one HTML paragraph (`<p> Entire chapter here </p>`).

Since I cannot share that book as it is copyrighted, I took the reference book which is in Public Domain and modified Chapter 1 so that the entire chapter is written inside a single paragraph block. With this change, I was able to reproduce the problem.
![Screenshot 2023-10-27 at 15 39 43](https://github.com/readium/kotlin-toolkit/assets/11408459/e437a3db-cd11-4a23-83a6-36c908978dd9)
![Screenshot 2023-10-27 at 15 41 21](https://github.com/readium/kotlin-toolkit/assets/11408459/f2408343-9e5b-45c3-bda8-d08042c12671)

🎞️ **Please see this attached video:**

https://github.com/readium/kotlin-toolkit/assets/11408459/b10403c8-2c9c-4d78-be07-4143dc22dad9

### Expected behavior

The e-reader should not jump backwards while highlighting text.

### How to reproduce?

1. Prepare the epub file:
a. Option 1: Download the file prepared by me as described above: https://www.dropbox.com/scl/fi/h8mlzoqaq2e4e5w76n5qi/md-edited.epub?rlkey=vvi2bknht0adrqgdxr0j9tvux&dl=1
b. Option 2: Get an epub file and modify it so that the entire chapter is contained in a single paragraph block
2. Import the epub in the sample app
3. Navigate to chapter 1 (if you used my file), then go a few pages into the chapter
4. Highlight something

### Environment

* Readium version: 2.3.0

#### Development environment

* OS: macOS 14.0
* IDE: Android Studio Giraffe | 2022.3.1 Patch 1

#### Testing device

* Android version: 13
* Model: Samsung SM-A536B
* Is it an emulator? No

### Additional context

* Are you willing to fix the problem and contribute a pull request? No

I have also seen the issue reported [here](https://github.com/readium/kotlin-toolkit/issues/284), but was closed before it was investigated in the sample app.

The same ebook works fine on iOS.

**Comment by mickael-menu** [comment]
This is a bug in the Chrome Web View, see this issue for more information: https://github.com/readium/kotlin-toolkit/issues/325
