### ISSUE TITLE
Cannot move on the start of the chapter

### ISSUE THREAD

**Issue by RomanSoviak** [readium/kotlin-toolkit#429]
In the Readium test app and our custom implementation moving on chapters doesn't work on one of our epub files. See the video below:

https://github.com/readium/kotlin-toolkit/assets/26696190/66f0b28b-1b91-4752-828e-8ac3a698abfe

**Comment by mickael-menu** [comment]
Hi, please follow the bug report issue template to make sure we can reproduce the issue in the same conditions: https://github.com/readium/kotlin-toolkit/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by RomanSoviak** [comment]
In version 2.3.0 everything works correctly
