### ISSUE TITLE
Error messages on the epub pages

### ISSUE THREAD

**Issue by RomanSoviak** [readium/kotlin-toolkit#430]
On some of our pages after changing font size we get the following error:
![image](https://github.com/readium/kotlin-toolkit/assets/26696190/9c38ae38-934e-4923-948b-c36b0007ee8a)
![image](https://github.com/readium/kotlin-toolkit/assets/26696190/85dee383-49a3-4d3e-bd6a-82f16ff2822c)
![image](https://github.com/readium/kotlin-toolkit/assets/26696190/ccd9f83a-8713-42de-8f53-03ffd81b4f8e)

**Comment by mickael-menu** [comment]
Hi, please follow the bug report issue template to make sure we can reproduce the issue in the same conditions: https://github.com/readium/kotlin-toolkit/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
