### ISSUE TITLE
Test App freezes after tapping on epub

### ISSUE THREAD

**Issue by RomanSoviak** [readium/kotlin-toolkit#436]
### Describe the bug

I downloaded the latest version of the Readium test app from here: https://github.com/readium/kotlin-toolkit/releases
The app froze after I tried to open my local epub. After a while I see the message: **App is not responding**
In the previous version everything of Readium (2.3.0) everything works good

https://github.com/readium/kotlin-toolkit/assets/26696190/8f6986b1-5ec6-4911-a4a7-b18e0fa245a3

### How to reproduce?

1. Install the test app from here: https://github.com/readium/kotlin-toolkit/releases
2. Get book from local storage
2. Tap on cover for opening epub

### Readium version

2.4.0

### Android API version

My device: Samsung M31. Android version: 12

**Comment by qnga** [comment]
Note: Jsoup's `NodeTraversor` takes far too much time. 2.3 and 3.0 don't have this issue if you don't start TTS because content iterator is lazy loaded.

**Comment by RomanSoviak** [comment]
Ok, so, the solution is to use 2.3 or 3.0 version?

**Comment by qnga** [comment]
That would be a good solution. We might fix it in a 2.4.1 sooner or later, but it's not our priority right now.
