### ISSUE TITLE
LCP Service always return failed [Bug] 

### ISSUE THREAD

**Issue by MohammedKarman80** [readium/kotlin-toolkit#471]
### Describe the bug

I added the additional dependencies that is required for LCP and even though i am still getting Exception("liblcp is missing on the classpath") when ever i call the LCP service .

### How to reproduce?

when i try to open any lcp bbok

### Readium version

2.4.0

### Android API version

all

**Comment by llemeurfr** [comment]
Are you from a company already in touch with EDRLab for the LCP lib?

**Comment by mickael-menu** [comment]
Please contact EDRLab for setting up the private library, we can't discuss it publicly on GitHub.
