### ISSUE TITLE
[Bug] Upgrading to 3.0.0-beta.2 causes desugaring error.

### ISSUE THREAD

**Issue by mcpierce** [readium/kotlin-toolkit#551]
### Describe the bug

When I updated my project from Readium 2.4.1 to 3.0.0-beta.2 the build environment complains that it now "requires core library desugaring to be enabled". 

### How to reproduce?

1. Successfully build using Readium 2.4.1.
1. Upgrade dependency to Readium 3.0.0-beta.2
1. Immediately receive build complaint.

### Readium version

3.0.0-beta.2

### Android API version

24

**Comment by mickael-menu** [comment]
That's expected, see the migration guide: https://github.com/readium/kotlin-toolkit/blob/develop/docs/migration-guide.md#300-beta1
