### ISSUE TITLE
[Bug] PageScrollMode.CONTINUOUS is not working like it is working as expected

### ISSUE THREAD

**Issue by Shtibel** [readium/kotlin-toolkit#563]
### Describe the bug

On the Readium Kotlin and Readium Swift `PageScrollMode.CONTINUOUS` is not working as expected
When you get to the last page of the chapter you need to swipe left / right to move to the fist page of the next chapter

On the Readium WEB the Scroll Mode CONTINUOUS is working as expected
When you get to the last page of the chapter and you scroll down it moves to the fist page of the next chapter
When you get to the first page of the chapter and you scroll up it moves to the last page of the previews chapter

On WEB You can see an example [here](https://readium.firebaseapp.com/?epub=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Faccessible_epub_3)
You can see a video of how it works here 

https://github.com/user-attachments/assets/a3cabac0-fc3b-49e8-ab45-2d9e7902ec62

Why is it not working also on Android and Swift ?

### How to reproduce?

Just set `PageScrollMode.CONTINUOUS` and you will see the issue when you scroll and get to the end of the chapter

### Readium version

3.0.0

### Android API version

2.4.0

**Comment by mickael-menu** [comment]
It works as expected, as it is not supported. There's no plan to support continuous scrolling in the mobile toolkits right now.

> Just set PageScrollMode.CONTINUOUS and you will see the issue when you scroll and get to the end of the chapter

I'm not sure what you mean, `PageScrollMode.CONTINUOUS` doesn't exist in the Swift and Kotlin toolkits.

**Comment by Shtibel** [comment]
> It works as expected, as it is not supported. There's no plan to support continuous scrolling in the mobile toolkits right now.
> 
> > Just set PageScrollMode.CONTINUOUS and you will see the issue when you scroll and get to the end of the chapter
> 
> I'm not sure what you mean, `PageScrollMode.CONTINUOUS` doesn't exist in the Swift and Kotlin toolkits.

Hi @mickael-menu 
See [here](https://github.com/readium/kotlin-toolkit/blob/d3f806a34bfa3cfd5c2aeb4ed13dd19dc00b0077/readium/adapters/pspdfkit/navigator/src/main/java/org/readium/adapter/pspdfkit/navigator/PsPdfKitDocumentFragment.kt#L325) in the code

Can I know why it is not planned ?
This is a trivial scroll mode on other eBook readers so why is it not even planned for the awesome Readium toolkit ?

**Comment by qnga** [comment]
What you pointed out is an adapter to PSPDFKit API. That's not a Readium API.
Continuous scroll is quite tricky to implement with WebViews. We might consider supporting it when we work on a new reflowable navigator, but that's not our short-term priority.
