### ISSUE TITLE
[Bug] Navigator doesn't save the locator position when closing the app in background

### ISSUE THREAD

**Issue by fabiorbap** [readium/kotlin-toolkit#565]
### Describe the bug

I am using the `navigator.currentLocator` to get an update of where the position in the book is.
When the app is in the foreground and I'm using TTS, it all works fine - the `currentLocator` is updated as the TTS engine reads the text.
However, when I put the app in background, all the callbacks from the `EpubNavigatorFragment.Listener` and `EpubNavigatorFragment.PaginationListener` stop being called when the app is in the background (there is a service for the TTS to keep reading the book). 
So, even though the text keeps being read with the app in the background, the `navigator` doesn't update the position in the book.
I checked and it seems that's because the `navigator` is tied to the lifecycle of the view, so when I put the app in the background, the fragment goes to the paused state and so does the `navigator`.
It seems that the position stored in the `navigator` is the position when the app was put in the background. So, if the book was on position 5 and I put the app in the background and let the book be read until page 7 when I killed the app, when I reopened it the book would still open on page 5.
I would like to know if there's a way to keep updating the `navigator` so that I can get the updated `locator` even if the app is in the background.

### How to reproduce?

1. Open any book
2. Activate TTS
3. Let the TTS start reading the book
4. Put the app in the background while the text is still being read
5. Let the book be read for some time (making sure it has changed to the next page)
6. Kill the app
7. Reopen the app, go back to the book
8. The book will reopen in the position when the app is put in the background, not in the position where the TTS engine stops.

### Readium version

2.4.0

### Android API version

13

**Comment by qnga** [comment]
This is the expected behavior. When using the TTS, you should take the current locator from the `TtsNavigator`.
See the [test-app](https://github.com/readium/kotlin-toolkit/blob/160668d047b0f3c4d570935da7bbc7765e602a9a/test-app/src/main/java/org/readium/r2/testapp/reader/MediaService.kt#L94).

**Comment by fabiorbap** [comment]
@qnga I understand. However, I still haven't been able to find a way to save this location while the app is in the background. I see that the test app is in Readium 3.0.0, I'm currently using 2.3.0, is there any example for this in 2.3.0? Thanks

**Comment by qnga** [comment]
I'm not sure. The TTS engine available in 2.3 does not properly support background playing anyway (Android is likely to kill your app). Upgrade to 2.4.x, at least if this is something you care about.
