### ISSUE TITLE
[Bug] [TTS] Text to speech is stop playing after reading certain part of the book.

### ISSUE THREAD

**Issue by veeraglass** [readium/kotlin-toolkit#566]
### Describe the bug

In the readium test app, when the TTS was enabled and started reading the pages. After reading certain part of the pages, the  speech is getting stopped. User has to intervene to again continue reading. Please find the attached video for reference.

https://github.com/user-attachments/assets/baef6795-8320-4fac-b9e6-541a5e6a66cd

### How to reproduce?

1. Open the eBook
2. Enable TTS feature and play the ebook.
3. After sometime, speech is getting stopped.
4.If the play speed is normal, the speech will stop after 25 to 30 minutes of playing.
5.If we increase the speed of speech to 30 times, the speech is stopping after 3 minutes.

### Readium version

2.4.0

### Android API version

34

**Comment by mickael-menu** [comment]
I tried reproducing the issue from `develop` with x30 speech rate and it continued playing for more than an hour.

* Are you able to reproduce the problem in the Test App from `develop` (3.0)? We won't fix the issue in 2.4.0.
* Does it happen with any book or one particular book? If yes, can you send us the book?
* Does it always stop on the same utterance/phrase in your test book?

**Comment by veeraglass** [comment]
Hi Mickael,
Its working on 3.0.0-beta(develop branch). Can we add the fix to 2.4.0 version as hot fix.
Thanks

**Comment by mickael-menu** [comment]
As the 3.0.0 version is nearing release, we don't do hot fixes on 2.4 unless critical issues preventing the build.
I suggest you migrate to 3.0.0-beta already, which is pretty stable and already used in production by a few apps.
