### ISSUE TITLE
[Bug] Error prompted when opening a file

### ISSUE THREAD

**Issue by Elysifyre** [readium/kotlin-toolkit#578]
### Describe the bug

UserError: Publication looks corrupted.
ReadError.Decoding: An error occurred while attempting to decode the content.
DebugError: Resource not found at OEBPS/Fonts/ht.ttf in publication.

### How to reproduce?

Open book 

### Readium version

3.0.0

### Android API version

34

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Elysifyre** [comment]
> Could you share the book in question?
https://cowtransfer.com/s/09c20a7d1ee143 点击链接查看 [ 西游记 (吴承恩) (Z-Library).epub ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 mh8t64 查看；

**Comment by qnga** [comment]
The error looks correct: `OEBPS/Fonts/ht.ttf` is missing though referenced in `OEBPS/Styles/font.css`. It's an authoring error.
