### ISSUE TITLE
Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by hishampro5** [readium/kotlin-toolkit#584]
### Describe the bug

I get this crash from **firebase_Crashlytics**  and i can't reproduce it on develop .

Device Details :
Model: Redmi Note 13 Pro+ 5G
android 14

I think this occurs on => ( PlayerService )

can you help me on this : 

Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{260fad9 u0 com.samawy.readerapp/.readium.MediaService}
   

### How to reproduce?

this occurs on  Redmi Note 13 Pro+ 5G and i can't reproduce it on develop env

### Readium version

2.4.3

### Android API version

14 

### Additional context

Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{260fad9 u0 com.samawy.readerapp/.readium.MediaService}

I copied same PlayerService class from TestApp

**Comment by mickael-menu** [comment]
There are some fixes on 3.0.0 to alleviate some of these crashes, but we can't prevent all of them as there's an issue in Jetpack media3 especially on Samsung devices https://github.com/androidx/media/issues/167

If you don't use audiobooks in your app, you can also disable the `MediaService` altogether.
