### ISSUE TITLE
[Bug] TTS Starts from Incorrect Position Instead of Current Page in EpubNavigatorFragment

### ISSUE THREAD

**Issue by engasix** [readium/kotlin-toolkit#596]
### Describe the bug

I’ve encountered an issue with the TTS functionality in `EpubNavigatorFragment`. When I start TTS from the current page, it does not begin reading from the visible text on that page. Instead, it jumps to the beginning of the chapter (e.g., Chapter 2, Page 1) regardless of the current position (e.g., Chapter 2, Page 6).

This behavior breaks the synchronization between the TTS and the user's current reading position, which can be confusing and disrupt the reading experience.

**Steps to Reproduce:**
- Open an EPUB file using `EpubNavigatorFragment`.
- Navigate to a specific page within a chapter (e.g., Chapter 2, Page 6).
- Start TTS from the current page.
- Observe that the TTS begins from the start of the chapter instead of the current visible text.

**Expected Behavior:**
TTS should start reading from the visible text of the current page as indicated by currentLocator.

**Actual Behavior:**
TTS starts from the beginning of the chapter, ignoring the current page position.

**Additional Context:**
I verified that currentLocator provides the correct CFI for the current position, so this issue seems related to how TTS initializes the reading position from the content.

**Environment Details:**
Library version: 3.0.0
Android version: 11, 12, 13
Device: Emulator + Xiaomi 

**Steps Taken:**
I attempted to work around this by implementing a custom TTS solution using currentLocator, but Readium doesn’t provide a straightforward way to extract content tied to the exact position within a page.

**Request:**
Please provide a fix or guidance on how to ensure TTS begins from the correct position within the current page. If additional details are needed, let me know.

Thank you for your hard work on this project!

### How to reproduce?

**Steps to Reproduce:**
- Open an EPUB file using `EpubNavigatorFragment`.
- Navigate to a specific page within a chapter (e.g., Chapter 2, Page 6).
- Start TTS from the current page.
- Observe that the TTS begins from the start of the chapter instead of the current visible text.

### Readium version

3.0.0

### Android API version

34

### Additional context

**Additional Context:**
I verified that currentLocator provides the correct CFI for the current position, so this issue seems related to how TTS initializes the reading position from the content.

**Comment by qnga** [comment]
I can't reproduce this on the testapp. Did you give it a try? Maybe the bug occurs only with a specific book?

**Comment by engasix** [comment]
@qnga
Thank you for your reply!

Yes, I have tested this with multiple books, and the behavior remains the same. I also observed the same issue in the TestApp.

**Comment by qnga** [comment]
For technical reasons (DOM element spanning over multiple pages), the TTS can start from the previous page, which in some (rare) cases can match the start of the chapter. If it is not the case you describe, please provide a book with a location to start the TTS from.

**Comment by engasix** [comment]
Hi @qnga and team,

Thank you for looking into this issue. I've created a video to demonstrate the problem with the TTS feature. Here's a quick overview of the video:

1. **Readium TestApp:**

- Opened two different books one by one in the official Readium TestApp.
- Observed and recorded the issue where TTS starts reading from the beginning of the chapter instead of the current page.

2. **My Application:**

- Showed similar behavior in the app I developed, which uses Readium.
- The issue seems consistent with the TestApp, suggesting it's not specific to my implementation.

You can watch the video here: [[YouTube Link]](https://youtube.com/shorts/KwZzMGHasP0?feature=share)

I hope this helps clarify the problem further. Let me know if there's anything else I can provide to assist with debugging!

**Comment by qnga** [comment]
Thanks for the video. It looks to me that most of the time the TTS does NOT start from the beginning of the chapter. It does so only once because the current position is in the middle of the first block element of the chapter.
As I mentioned earlier, the TTS is not supposed to start from the current page, but from the start of the current block element, which is most of the time on the previous page. So this is the expected behavior. Doing something better is hard or impossible,
