### ISSUE TITLE
Android device's app not calling registration endpoint

### ISSUE THREAD

**Issue by SergioPMA** [readium/kotlin-toolkit#599]
Hello,
I've setup a LCP server and test frontend.
I've created some licenses, either loan and buy.
When I open the corresponding .lcpl files with Thorium desktop, the device gets registered thru the endpoint: 

> POST <LSDbaseURL>/licenses/<license_id>/register{?id, name}

and the license status changes from _ready_ to _active_.

But if I use an Android app like R2 reader (I tried also MLOL app and Torrossa), the device is not registered, the register endpoint is not called and the license stucks on _ready_ state, but I can open and view the document related to .lcpl license.

In the documentation I can read that the call to register endpoint is mandatory, but it's not.

What's the problem? There's something I'm doing wrong?

Thank you

**Comment by mickael-menu** [comment]
I checked with the Kotlin toolkit 3.0.2 and the `register` endpoint is called properly when opening a license for the first time.

From your description, my guess is that the Android app cannot reach the LSD server through your local network. Can you share the LCPL file as well as the content returned by the `status` endpoint listed in the LCPL file?

**Comment by SergioPMA** [comment]
Hi Mickael,
here's the lcpl file (I had to rename it as .txt to let github upload it):
[random.lcpl.txt](https://github.com/user-attachments/files/18112436/random.lcpl.txt)
and this is the response given by `status` endpoint:
```
{
  "id": "d8c3c68c-f576-4329-a94a-a341ac66cdc7",
  "status": "ready",
  "updated": {
    "license": "2024-12-12T10:56:04Z",
    "status": "2024-12-12T10:56:04Z"
  },
  "message": "The license is in ready state",
  "links": [
    {
      "rel": "license",
      "href": "https://api.librosicuro.it/license/licenses/d8c3c68c-f576-4329-a94a-a341ac66cdc7",
      "type": "application/vnd.readium.lcp.license.v1.0+json"
    },
    {
      "rel": "register",
      "href": "http://api.librosicuro.it/status/licenses/d8c3c68c-f576-4329-a94a-a341ac66cdc7/register{?id,name}",
      "type": "application/vnd.readium.license.status.v1.0+json",
      "templated": true
    }
  ]
}
```
The server is reachable by Android device, here's a apache log entry of the device requesting license status:
`212.97.64.5 - - [12/Dec/2024:10:57:33 +0000] "GET /status/licenses/d8c3c68c-f576-4329-a94a-a341ac66cdc7/status HTTP/1.1" 200 3407 "-" "Dalvik/2.1.0 (Linux; U; Android 14; 2312DRA50G Build/UKQ1.231003.002)"`
Note: the Android device is connected through a VPN provider.

**Comment by mickael-menu** [comment]
I don't see anything wrong in your license or the status document.

Are you able to start the R2 Reader app from Android Studio to debug and see the logs? You should be able to put a breakpoint there to see if registers the device: https://github.com/readium/kotlin-toolkit/blob/b77fa792684335b92d1cc23f17e4c540c14953d6/readium/lcp/src/main/java/org/readium/r2/lcp/license/LicenseValidation.kt#L466

Also I would try deleting the app and reinstalling it in case the device was already registered earlier. It is done only once.
