### ISSUE TITLE
PDF Navigator: Supporting RTL reading progression metadata

### ISSUE THREAD

**Issue by mickael-menu** [readium/kotlin-toolkit#66]
The PDF specification allows to set the reading progression in the document's metadata. It is available under the `ViewerPreferences/Direction` object.

I implemented the retrieval of this metadata to infer the `publication.metadata.readingProgression` value [on the Swift toolkit](https://github.com/readium/swift-toolkit/pull/22), but it's more challenging on Android.

The low-level API we need ([`FPDF_VIEWERREF_GetName`](https://pdfium.googlesource.com/pdfium.git/+/04bebfe590d6d27a825b881fd234e31501843edc)) is available in a newer version of PDFium than the one used by [PdfiumAndroid](https://github.com/barteksc/PdfiumAndroid). Upgrading this dependency could be challenging, see this [related issue](https://github.com/readium/kotlin-toolkit/issues/29).

**Comment by qnga** [comment]
As only LTR and RTL are available, I suppose `ViewerPreferences/Direction` doesn't match the reading progression in the Readium sense. Shouldn't `TTB` be the default `readingProgression` for every PDF?
`ViewerPreferences/Direction` would still be useful to determine spread direction though. @HadrienGardeur How are we supposed to express it in RWPM?

It's very confusing. According to the spec:
> To properly browse through a publication, a User Agent needs to know its progression direction.
In that sense, `ViewerPreferences/Direction` is the correct direction (of he publication).

As far as I understood from discussions, `readingProgression` would rather mean "which direction the user has to do some gesture to move forward".

**Comment by mickael-menu** [comment]
With the new settings API, we changed the possible values of `readingProgression`, only `ltr` and `rtl` are valid. This is the same meaning as `ViewerPreferences/Direction`.

The reading progression is supported with PSPDFKit, but won't be for PDFium.
