### ISSUE TITLE
Simplify dependency versioning and referencing with Gradle version catalogs

### ISSUE THREAD

**Issue by stevenzeck** [readium/kotlin-toolkit#75]
See https://docs.gradle.org/current/userguide/platforms.html.  As discussed on Slack, it would be great to have common dependencies reference the same version number so that all modules use the same version.  For example, `org.jetbrains.kotlinx:kotlinx-coroutines-core`.

Although this can be done right now, it is still in Gradle Feature Preview, plus Android Studio doesn't support it very well; it doesn't suggest when an update is available for a dependency and the dependencies don't even show up in the Project Structure.  A [`libs.versions.toml`](https://github.com/readium/kotlin-toolkit/blob/4b61ad5e31f66e078a2a7bc308d3a5e6e4312ae8/gradle/libs.versions.toml2) file was started, and can be built from that when the time is right.

**Comment by mickael-menu** [comment]
Implemented in https://github.com/readium/kotlin-toolkit/pull/283
