### ISSUE TITLE
Fixed-layout font-size affected by device settings

### ISSUE THREAD

**Issue by TamJ** [readium/kotlin-toolkit#76]
## Bug Report

One issue that we’re experiencing concerns font-size for EPUB3 fixed-layout titles in Android. For titles opened in Android, the text font may be enlarged if the OS settings for text size are set above ‘Normal’.
 
Are the Readium team aware of this issue? Is it possible to restrict the OS access to font-size in Readium when the EPUB3 file is rendition:layout pre-paginated?

Attached screenshots: 
Normal, when device text size is set to 'Normal'
Extra large, when device text size is set higher than normal.
![Normal-size_20211229_173819_com aldiko android](https://user-images.githubusercontent.com/5805844/147686101-95fbbd57-82a1-4ed4-acb7-41ee800bc847.jpg)

* Readium version:

#### Development environment

* OS: Huawei P30
App: Adilko
Android version: 9

![Extra-large_20211229_173858_com aldiko android](https://user-images.githubusercontent.com/5805844/147686397-575e3d29-c1b9-471a-9a9b-d165e6e0c24c.jpg)

**Comment by mickael-menu** [comment]
Thanks for reporting this issue, I opened a twin issue on Readium CSS to discuss this in more depth: https://github.com/readium/readium-css/issues/115
