### ISSUE TITLE
Can't open .lcpl protected files

### ISSUE THREAD

**Issue by bv33** [readium/kotlin-toolkit#77]
### What happened?
When trying to open a file with .lcpl extension which is protected with password the following error message appears:
"Error: This License has a profile identifier that this app cannot handle, the publication cannot be..."
![Screenshot_20211231-021403_R2 Reader](https://user-images.githubusercontent.com/31557609/147795933-5450e0f5-ca94-4f5d-b603-2598cfe84a1a.jpg)

### Expected behavior

To open the file normally with no errors like Thorium Reader on desktop devicses
### How to reproduce?
The ebook is successfully downloaded and the book cover appears, but when trying to open it it doesn't load or ask for the password and the previous error message appears

### Environment

* Readium version: 2.2.0 [Downloaded and installed the apk file today from the latest release]

#### Development environment

* OS: 
* IDE: 

#### Testing device

* Android version: 10
* Model: Samsung Galaxy M31
* Is it an emulator? No

### Additional context

* Are you willing to fix the problem and contribute a pull request? Yes or No

**Comment by stevenzeck** [comment]
What is the profile identifier in the lcpl file in question?

**Comment by bv33** [comment]
I have tested lcpl files from two sources:
1- LCP license samples from EDRLab's official website. ([link](https://www.edrlab.org/readium-lcp/testing-readium-lcp-compliant-devices/))
2- eBook DRM service called "EditionGuard" used in my organization to protect its published ebooks.

**Comment by mickael-menu** [comment]
You can't use a production license with the Test App, only test ones.

To generate test licenses, you can use https://front-test.edrlab.org

Please contact EDRLab if you need more help regarding this particular issue.

**Comment by bv33** [comment]
Thanks for your reply.
Can you please explain more about how to generate test licenses using the mentioned link?
