### ISSUE TITLE
Moving to previous page when selecting text

### ISSUE THREAD

**Issue by jmgeffroy** [readium/kotlin-toolkit#86]
When doing a selection where the end position x is > to the start position x, this is interpreted as a "swipe towards right" gesture, and it moves to the previous page. The selection pop-up menu allears on the new page, whereas the selection is where it should be, on the page that just disappeared. Tested in R2 testapp, develop, and a R2-based app. 
- Page with the pop-up (incorrect)
![Screenshot_20220214-182601_Aldiko](https://user-images.githubusercontent.com/4281439/153933666-5c5b9098-5b2b-4463-9994-574413a4e0be.jpg)
- Page with the selection:
![Screenshot_20220214-182647_Aldiko](https://user-images.githubusercontent.com/4281439/153933715-d9fd46e1-b952-4e94-8081-d855bfb6350a.jpg)

**Comment by mickael-menu** [comment]
Fixed in https://github.com/readium/kotlin-toolkit/pull/143
