### ISSUE TITLE
A glitch when when navigating from chapter to chapter.

### ISSUE THREAD

**Issue by javlonrahimov** [readium/kotlin-toolkit#87]
When navigating through pages it is working well but when we navigate from chapter to chapter the transition is not being smooth.

https://user-images.githubusercontent.com/56770292/154473069-51137103-eda0-40ad-b36c-9cb78f2bae10.mp4

**Comment by mickael-menu** [comment]
This is not a bug but a technical limit of the current navigator implementation. We'll try to improve things with [Navigator2](https://github.com/readium/kotlin-toolkit/discussions/51).
