### ISSUE TITLE
Accessing MediaNavigator outside AudioReaderFragment

### ISSUE THREAD

**Issue by filippocacciotto** [readium/kotlin-toolkit#96]
Hi everybody. 

I replicated the testapp architecture in order to add audiobooks to the e-reader app I'm currently working on. Right now, in my repo I have a LiveData for the book list that's taken directly from the db and I'm observing its changes in my LibraryFragment, in order to update the list of available publications. The problem with audiobooks is that when the playback continues in background after leaving the AudioReaderFragment, since the service constantly saves the new progression inside the db, the observer awakes and the list is reload from memory, causing the recycler view to flicker continuously. 

Therefore, I'd need a way to detect when the user stops the playback of a book while being outside the AudioReaderFragment (i.e. when the user presses the "stop" button of the ExoPlayer notification while being in the LibraryFragment, for example), in order to "disable" the observer while the playback is going on and "enable" it again when the playback is stopped.

The smoothest way would be observing the playback property of the MediaNavigator but I don't know how to access it once I leave the AudioReaderFragment (where I connect to the service and start the playback). I also tried to analyze the code in order to find a callback that could help me but, after putting a log inside every MediaService and MediaPlayer.Listener callback, I saw that the only one that's never called (even when I tap on the stop button) is onPlayerStopped(), which is also the one that could be right for my situation. Is it correct that's never called? What other strategies could I follow in this situation?

Thanks in advance for your help.

**Comment by mickael-menu** [comment]
To answer directly to your question: How to access the currently playing `MediaNavigator`? You need to first connect to the `MediaService` using your app subclass (`AudiobookService` in the test app). For example:

```kotlin
val mediaService = MediaService.connect(AudiobookService::class.java)
val mediaNavigator = mediaService.currentNavigator
```

But IMO, the proper way to address the flickering problem is to only update your views when properties that are visible to the user change, not when any property of the database entity changes. This can be handled either by:

1. [Querying only a subset of your entity's columns](https://developer.android.com/training/data-storage/room/accessing-data#return-subset) with Room, the ones that are actually displayed.
2. Comparing only the properties that influence the view in your `DiffUtil.ItemCallback` implementation.

[In the Test App we are doing number 2 for simplicity](https://github.com/readium/kotlin-toolkit/blob/adeb8f452fbd48b6ab7e1132264bcce9ab64ee95/test-app/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfAdapter.kt#L75-L83), but in a real app I would do 1.
