### ISSUE TITLE
Java interoperability

### ISSUE THREAD

**Issue by qnga** [readium/kotlin-toolkit#98]
Some issues with Java interoperability were reported to me:
- Default arguments are not available, which makes the code difficult to use (for instance, the `Streamer` constructor). This shortcoming could probably be overcome with the @JvmOverloads annotation.
- For some unknown reason, `DefaultHttpClient` looks private from Java.

As I'm not sure we want to support Java and the reporter has eventually decided to use Kotlin, this issue is mainly for the record.

**Comment by mickael-menu** [comment]
We decided on the last dev call that Java interoperability is not a goal for the Kotlin toolkit, as virtually all stakeholders are using Kotlin nowadays.

If an implementer has a vested interest in supporting Java for some of the Kotlin toolkit modules, we are open to review contributions. Feel free to chime in on this issue before opening a PR, to discuss about the required changes.
